include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # All default Flutter lints enabled
    # Can customize by uncommenting rules here

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
